<a href="https://colab.research.google.com/github/JulianMeigen/ML-handson/blob/main/notebooks/8.0-SNJMMH-Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Day 8

## Team members:
- Samuel Nebgen s6sanebg@uni-bonn.de
- Muhammad Humza Arain s27marai@uni-bonn.de
- Julian Meigen s82jmeig@uni-bonn.de

## 17.09.2025

Contributions were made by all team members in around the same amount, either based on discussions or coding.

# Task 1: Understand the dataset

In [78]:
!gdown --folder https://drive.google.com/drive/folders/1w_3J7hXOKd4IEEkQp25c0-3-IU1Qqmzp?usp=sharing

Retrieving folder contents
Processing file 1i-YvTQv7dO4EhsZoIFbQj6WJWRNdTZ16 hungary_chickenpox.csv
Processing file 1idipHj2FqgyKfhDqVne3xRyVxW5gnqEq hungary_county_edges.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1i-YvTQv7dO4EhsZoIFbQj6WJWRNdTZ16
To: /content/Day_8/hungary_chickenpox.csv
100% 35.1k/35.1k [00:00<00:00, 45.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1idipHj2FqgyKfhDqVne3xRyVxW5gnqEq
To: /content/Day_8/hungary_county_edges.csv
100% 1.85k/1.85k [00:00<00:00, 5.18MB/s]
Download completed


## a) Load the dataset Hungarian Chickenpox

In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import os



In [80]:
chickenpox_features_dataset = pd.read_csv(os.path.join('Day_8', 'hungary_chickenpox.csv'), index_col=0)
chickenpox_edges_dataset = pd.read_csv(os.path.join('Day_8', 'hungary_county_edges.csv'))

## b) Identify the number of edges, nodes, and temporal features.

In [81]:
print(f'The number of edges in the dataset is {chickenpox_edges_dataset.shape[0]}')

The number of edges in the dataset is 102


In [82]:
print(f'The number of nodes in the dataset is {chickenpox_features_dataset.shape[1]}')


The number of nodes in the dataset is 20


In [83]:
print(f'The number of temporal features is {chickenpox_features_dataset.shape[0]}')

The number of temporal features is 522


## c) Plot the adjacency matrix of the counties.

In [84]:
adjacency_matrix = np.zeros((chickenpox_features_dataset.shape[1], chickenpox_features_dataset.shape[1]))

for id_1, id_2 in zip(chickenpox_edges_dataset['id_1'], chickenpox_edges_dataset['id_2']):
    adjacency_matrix[id_1, id_2] = 1
    adjacency_matrix[id_2, id_1] = 1


header = list(chickenpox_edges_dataset['name_1'].unique())
index = list(chickenpox_edges_dataset['name_1'].unique())
adjacency_df = pd.DataFrame(data = adjacency_matrix, columns=header, index=index)

adjacency_df

BACS  BARANYA  BEKES  BORSOD  BUDAPEST  CSONGRAD  FEJER  GYOR  \
BACS       1.0      1.0    0.0     0.0       0.0       1.0    1.0   0.0   
BARANYA    1.0      1.0    0.0     0.0       0.0       0.0    0.0   0.0   
BEKES      0.0      0.0    1.0     0.0       0.0       1.0    0.0   0.0   
BORSOD     0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
BUDAPEST   0.0      0.0    0.0     0.0       1.0       0.0    0.0   0.0   
CSONGRAD   1.0      0.0    1.0     0.0       0.0       1.0    0.0   0.0   
FEJER      1.0      0.0    0.0     0.0       0.0       0.0    1.0   0.0   
GYOR       0.0      0.0    0.0     0.0       0.0       0.0    0.0   1.0   
HAJDU      0.0      0.0    1.0     1.0       0.0       0.0    0.0   0.0   
HEVES      0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
JASZ       1.0      0.0    1.0     1.0       0.0       1.0    0.0   0.0   
KOMAROM    0.0      0.0    0.0     0.0       0.0       0.0    1.0   1.0   
NOGRAD     0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
PEST       1.0      0.0    0.0     0.0       1.0       0.0    1.0   0.0   
SOMOGY     0.0      1.0    0.0     0.0       0.0       0.0    1.0   0.0   
SZABOLCS   0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
TOLNA      1.0      1.0    0.0     0.0       0.0       0.0    1.0   0.0   
VAS        0.0      0.0    0.0     0.0       0.0       0.0    0.0   1.0   
VESZPREM   0.0      0.0    0.0     0.0       0.0       0.0    1.0   1.0   
ZALA       0.0      0.0    0.0     0.0       0.0       0.0    0.0   0.0   

          HAJDU  HEVES  JASZ  KOMAROM  NOGRAD  PEST  SOMOGY  SZABOLCS  TOLNA  \
BACS        0.0    0.0   1.0      0.0     0.0   1.0     0.0       0.0    1.0   
BARANYA     0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
BEKES       1.0    0.0   1.0      0.0     0.0   0.0     0.0       0.0    0.0   
BORSOD      1.0    1.0   1.0      0.0     1.0   0.0     0.0       1.0    0.0   
BUDAPEST    0.0    0.0   0.0      0.0     0.0   1.0     0.0       0.0    0.0   
CSONGRAD    0.0    0.0   1.0      0.0     0.0   0.0     0.0       0.0    0.0   
FEJER       0.0    0.0   0.0      1.0     0.0   1.0     1.0       0.0    1.0   
GYOR        0.0    0.0   0.0      1.0     0.0   0.0     0.0       0.0    0.0   
HAJDU       1.0    0.0   1.0      0.0     0.0   0.0     0.0       1.0    0.0   
HEVES       0.0    1.0   1.0      0.0     1.0   1.0     0.0       0.0    0.0   
JASZ        1.0    1.0   1.0      0.0     0.0   1.0     0.0       0.0    0.0   
KOMAROM     0.0    0.0   0.0      1.0     0.0   1.0     0.0       0.0    0.0   
NOGRAD      0.0    1.0   0.0      0.0     1.0   1.0     0.0       0.0    0.0   
PEST        0.0    1.0   1.0      1.0     1.0   1.0     0.0       0.0    0.0   
SOMOGY      0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
SZABOLCS    1.0    0.0   0.0      0.0     0.0   0.0     0.0       1.0    0.0   
TOLNA       0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
VAS         0.0    0.0   0.0      0.0     0.0   0.0     0.0       0.0    0.0   
VESZPREM    0.0    0.0   0.0      1.0     0.0   0.0     1.0       0.0    0.0   
ZALA        0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    0.0   

          VAS  VESZPREM  ZALA  
BACS      0.0       0.0   0.0  
BARANYA   0.0       0.0   0.0  
BEKES     0.0       0.0   0.0  
BORSOD    0.0       0.0   0.0  
BUDAPEST  0.0       0.0   0.0  
CSONGRAD  0.0       0.0   0.0  
FEJER     0.0       1.0   0.0  
GYOR      1.0       1.0   0.0  
HAJDU     0.0       0.0   0.0  
HEVES     0.0       0.0   0.0  
JASZ      0.0       0.0   0.0  
KOMAROM   0.0       1.0   0.0  
NOGRAD    0.0       0.0   0.0  
PEST      0.0       0.0   0.0  
SOMOGY    0.0       1.0   1.0  
SZABOLCS  0.0       0.0   0.0  
TOLNA     0.0       0.0   0.0  
VAS       1.0       1.0   1.0  
VESZPREM  1.0       1.0   1.0  
ZALA      1.0       1.0   1.0

### Other approach (Loading it in torch_geometric.data.Data object)

In [85]:
!pip install torch_geometric

In [86]:
from torch_geometric.data import Data
from torch_geometric.utils import to_dense_adj
import torch


In [87]:
# get Adj List
edge_list = torch.tensor(chickenpox_edges_dataset[["id_1", "id_2"]].to_numpy(), dtype=torch.long)
print(edge_list[:3])
print()

# Convert to torch geometric data object
data = Data(x=chickenpox_features_dataset.values, edge_index=edge_list.t().contiguous())

# Add information
data.num_nodes = data.x.shape[1]
data.num_temp_features = data.x.shape[0]

# Add additional information to the data object
data.dates = chickenpox_features_dataset.index.tolist() # Need to convert it back to a list because PyG does not support pd.DatetimeIndex
data.county_names = chickenpox_features_dataset.columns.tolist()

# b)
# Number of nodes:
print("Number of nodes: ", data.num_nodes)

# Number of edges:
print("Number of edges: ", data.num_edges)

# Number of temporal features per node:
print("Number of temporal features per node: ", data.num_temp_features)
print()
print(data)



tensor([[ 0, 10],
        [ 0,  0],
        [ 0,  1]])

Number of nodes:  20
Number of edges:  102
Number of temporal features per node:  522

Data(x=[522, 20], edge_index=[2, 102], num_nodes=20, num_temp_features=522, dates=[522], county_names=[20])


In [88]:
# c)
adj_mat = to_dense_adj(data.edge_index, max_num_nodes=data.num_nodes).squeeze().numpy()
print(adj_mat)


[[1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.

# Task 2: Load the dataset into pytorch-geometric-temporal.

## a) Load the dataset with the class: ChickenpoxDatasetLoader

In [89]:
!pip install torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-2.8.0+cu126.html

Looking in links: https://data.pyg.org/whl/torch-2.8.0+cu126.html


In [90]:
!pip install torch_geometric_temporal

In [91]:
from torch_geometric_temporal.dataset import ChickenpoxDatasetLoader

loader = ChickenpoxDatasetLoader()

dataset = loader.get_dataset()

## b) Identify the differences between loading the raw dataset from Task 1 and the processed dataset from this task.

In [92]:
print(dataset[0])

Data(x=[20, 4], edge_index=[2, 102], edge_attr=[102], y=[20])


In [93]:
print(dataset.features[0][0:2])

[[-1.08135724e-03  2.85705967e-02  3.54742090e-01  2.95438182e-01]
 [-7.11136085e-01 -5.98430173e-01  1.90511208e-01  1.09215850e+00]]


In [94]:
print(dataset.targets[0][0:2])

[ 0.71056554 -0.07246925]


Because the Labels have been removed, we need to map the county IDs later back to the raw dataset.

# Task 3: Define a model using pytorch-geometric-temporal

## i. Split the dataset into train and test.

In [95]:
from torch_geometric_temporal.signal import temporal_signal_split

In [96]:
train_dataset, test_dataset = temporal_signal_split(dataset, train_ratio=0.8)


print(train_dataset[0])
print(test_dataset[0])
print(len(list(train_dataset)))
print(len(list(test_dataset)))

Data(x=[20, 4], edge_index=[2, 102], edge_attr=[102], y=[20])
Data(x=[20, 4], edge_index=[2, 102], edge_attr=[102], y=[20])
413
104


In [97]:
#for time, snapshot in enumerate(train_dataset):
#    print(f'Time {time}:')
#    print('snapshot', snapshot)


## ii. Train your model on the training dataset


In [98]:
#implement the model
torch.manual_seed(1)
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import DCRNN

class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features, out_channels=32, K=1):
        super(RecurrentGCN, self).__init__()
        self.recurrent = DCRNN(node_features, out_channels, K)
        self.linear = torch.nn.Linear(out_channels, 1)

    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight)
        h = F.relu(h)
        h = self.linear(h)
        return h

In [99]:
#train the model
from tqdm import tqdm
model = RecurrentGCN(node_features=4)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model.train()

for epoch in tqdm(range(200)):
    cost = 0
    for time, snapshot in enumerate(train_dataset):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
    cost = cost / (time+1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()

  1%|          | 2/200 [00:04<07:27,  2.26s/it]


KeyboardInterrupt: 


## iii. Test your model on the test dataset and evaluate it for MSE.

In [ ]:
model.eval()
cost = 0
for time, snapshot in enumerate(test_dataset):
    y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
    cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
cost = cost / (time+1)
cost = cost.item()
print("MSE: {:.4f}".format(cost))

Since our target here is a continous variable and we are doing a Regression (Forecasting the Chickenpox counts based on previous counts), we use MSE (or RMSE), which sums up the squared differnece between the truth and the predicted value. Since it squares the errors, big differneces are stongly penalized but it is also sensitive to outliers.

Beacuse we are doing a regression task its better to use MSE or MAE. If we would do a classification task, metrics such as f1-score or accuracy or AUROC could be used.

# Task 4: Set up a hyperparameter optimization pipeline with nested 5-fold cross-validation.

## i. Familiarize yourself with the hyperparameter optimization package optuna (https://optuna.org/ ).


In [100]:
class RGCNoptimization:
    def __init__(self, train_dataset, val_dataset, input_feature=4, study_name="GCN_optimization"):
        self.data = data
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.input_feature = input_feature

        self.study_name = study_name
        self.storage_name = "sqlite:///{}.db".format(self.study_name)
        self.study = optuna.create_study(study_name=self.study_name, storage=self.storage_name, load_if_exists=True)

    def objective(self, trial):
        # Define the hyperparameters to optimize

        out_channels = trial.suggest_int("out_channels", 16, 128) # Changed from suggest_float to suggest_int
        K = trial.suggest_int("K", 1, 5)
        LR = trial.suggest_float("LR", 0.001, 0.1)

        # Create the GCN model with the suggested hyperparameters
        model = RecurrentGCN(self.input_feature, out_channels, K)

        # Train the model
        optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=5e-4)
        criterion = torch.nn.MSELoss()

        # Training loop
        epochs = 100
        model.train()
        for epoch in range(1, epochs + 1):
          loss = 0
          for time, snapshot in enumerate(self.train_dataset):
            optimizer.zero_grad()
            out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
            loss = loss + criterion(out, snapshot.y)

          loss = loss / (time+1)
          loss.backward()
          optimizer.step()


        # Validate the model
        model.eval()
        with torch.no_grad():
          loss = 0
          for time, snapshot in enumerate(self.val_dataset):
            optimizer.zero_grad()
            out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
            loss = loss + criterion(out, snapshot.y)
          loss = loss / (time+1)

        return loss.item()

## ii. Integrate the logging package mlflow (https://mlflow.org/) to log your metrics.


## iii. Train and test your models and report the evaluation metrics with mean and standard deviation for the nested CV.

In [101]:
!pip install optuna

In [102]:
!pip install wandb -q

In [103]:
import optuna

In [104]:
 #Ignore excessive warnings
import logging
logging.propagate = False
logging.getLogger().setLevel(logging.ERROR)

# WandB – Import the wandb library
import wandb

In [105]:
!wandb login

Traceback (most recent call last):
  File "/usr/local/bin/wandb", line 4, in <module>
    from wandb.cli.cli import cli
  File "/usr/local/lib/python3.12/dist-packages/wandb/cli/cli.py", line 41, in <module>
    from wandb.sync import SyncManager, get_run_from_path, get_runs
KeyboardInterrupt
^C


In [111]:
from sklearn.model_selection import TimeSeriesSplit

In [112]:
dataset.snapshot_count

517

In [113]:
1 - 10/517

0.9806576402321083

In [114]:
# getting last 10 Weeks as Model-test set which will be indepoendend of our training. Its needed to compare the models in the end.
data, model_test = temporal_signal_split(dataset, train_ratio= 1-10/517)

In [115]:
data.snapshot_count, model_test.snapshot_count

(507, 10)

In [ ]:
dataset_lst = list(data)
n_splits_outer = 5
tscv = TimeSeriesSplit(n_splits=3)

idx = np.arange(len(dataset_lst))
for train_val_idx, test_idx in tscv.split(idx):
  train_val_mask = np.isin(idx, train_val_idx)
  test_mask = np.isin(idx, test_idx)

  train_val_dataset_lst = [i for idx, i in enumerate(dataset_lst) if train_val_mask[idx]]
  test_dataset_lst = [i for idx, i in enumerate(dataset_lst) if test_mask[idx]]

  ## Inner Loop
  tscv_inner = TimeSeriesSplit(n_splits=3)
  idx_inner = np.arange(len(train_val_dataset_lst))


  for train_idx, val_idx in tscv_inner.split(idx_inner):
    train_mask = np.isin(idx_inner, train_idx)
    val_mask = np.isin(idx_inner, val_idx)

    train_dataset_lst = [i for idx, i in enumerate(train_val_dataset_lst) if train_mask[idx]]
    val_dataset_lst = [i for idx, i in enumerate(train_val_dataset_lst) if val_mask[idx]]


    # Optimize/Train model with optuna
    gcn_op = RGCNoptimization(train_dataset_lst, val_dataset_lst, input_feature=4)
    study = gcn_op.study
    study.optimize(gcn_op.objective, n_trials=10)
    best_params = study.best_params

  ## End Inner Loop


  # Train the best param model
  model = RecurrentGCN(input_feature=4, out_channels=best_params["out_channels"], K=best_params["K"])
  optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
  criterion = torch.nn.MSELoss()

  # Training loop

  epochs = 100
  model.train()
  for epoch in range(1, epochs + 1):
    loss = 0
    for time, snapshot in enumerate(train_val_dataset_lst):
      optimizer.zero_grad()
      out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
      loss = loss + criterion(out, snapshot.y)

    loss = loss / (time+1)
    loss.backward()
    optimizer.step()


  # Validate the model
  model.eval()
  with torch.no_grad():
    loss = 0
    for time, snapshot in enumerate(test_dataset_lst):
      optimizer.zero_grad()
      out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
      loss = loss + criterion(out, snapshot.y)
    loss = loss / (time+1)

[I 2025-09-17 14:34:31,310] A new study created in RDB with name: GCN_optimization
/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([20])) that is different to the input size (torch.Size([20, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
[I 2025-09-17 14:34:43,833] Trial 0 finished with value: 0.9299585223197937 and parameters: {'out_channels': 41, 'K': 1, 'LR': 0.02706591029469021}. Best is trial 0 with value: 0.9299585223197937.
[I 2025-09-17 14:34:55,647] Trial 1 finished with value: 0.9065214991569519 and parameters: {'out_channels': 112, 'K': 1, 'LR': 0.06531538903996431}. Best is trial 1 with value: 0.9065214991569519.
[I 2025-09-17 14:35:38,219] Trial 2 finished with value: 0.9961458444595337 and parameters: {'out_channels': 112, 'K': 4, 'LR': 0.0691009642025934}. Best is trial 1 with value: 

# Task 5: Test implementations of 3 different models (such as GConvLSTM, GConvGRU, STGCN, DCRNN) and find out the best performing model


# Task 6: Compare your results with the following study: https://arxiv.org/abs/2102.08100