<a href="https://colab.research.google.com/github/JulianMeigen/ML-handson/blob/main/notebooks/8.0-SNJMMH-Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Day 8

## Team members:
- Samuel Nebgen s6sanebg@uni-bonn.de
- Muhammad Humza Arain s27marai@uni-bonn.de
- Julian Meigen s82jmeig@uni-bonn.de

## 17.09.2025

Contributions were made by all team members in around the same amount, either based on discussions or coding.

# Task 1: Understand the dataset

In [1]:
!gdown --folder https://drive.google.com/drive/folders/1w_3J7hXOKd4IEEkQp25c0-3-IU1Qqmzp?usp=sharing

Retrieving folder contents
Processing file 1i-YvTQv7dO4EhsZoIFbQj6WJWRNdTZ16 hungary_chickenpox.csv
Processing file 1idipHj2FqgyKfhDqVne3xRyVxW5gnqEq hungary_county_edges.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1i-YvTQv7dO4EhsZoIFbQj6WJWRNdTZ16
To: /content/Day_8/hungary_chickenpox.csv
100% 35.1k/35.1k [00:00<00:00, 54.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1idipHj2FqgyKfhDqVne3xRyVxW5gnqEq
To: /content/Day_8/hungary_county_edges.csv
100% 1.85k/1.85k [00:00<00:00, 5.87MB/s]
Download completed


## a) Load the dataset Hungarian Chickenpox

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import os



In [3]:
chickenpox_features_dataset = pd.read_csv(os.path.join('Day_8', 'hungary_chickenpox.csv'), index_col=0)
chickenpox_edges_dataset = pd.read_csv(os.path.join('Day_8', 'hungary_county_edges.csv'))

## b) Identify the number of edges, nodes, and temporal features.

In [4]:
print(f'The number of edges in the dataset is {chickenpox_edges_dataset.shape[0]}')

The number of edges in the dataset is 102


In [5]:
print(f'The number of nodes in the dataset is {chickenpox_features_dataset.shape[1]}')


The number of nodes in the dataset is 20


In [6]:
print(f'The number of temporal features is {chickenpox_features_dataset.shape[0]}')

The number of temporal features is 522


## c) Plot the adjacency matrix of the counties.

In [7]:
adjacency_matrix = np.zeros((chickenpox_features_dataset.shape[1], chickenpox_features_dataset.shape[1]))

for id_1, id_2 in zip(chickenpox_edges_dataset['id_1'], chickenpox_edges_dataset['id_2']):
    adjacency_matrix[id_1, id_2] = 1
    adjacency_matrix[id_2, id_1] = 1


header = list(chickenpox_edges_dataset['name_1'].unique())
index = list(chickenpox_edges_dataset['name_1'].unique())
adjacency_df = pd.DataFrame(data = adjacency_matrix, columns=header, index=index)

adjacency_df

BACS  BARANYA  BEKES  BORSOD  BUDAPEST  CSONGRAD  FEJER  GYOR  \
BACS       1.0      1.0    0.0     0.0       0.0       1.0    1.0   0.0   
BARANYA    1.0      1.0    0.0     0.0       0.0       0.0    0.0   0.0   
BEKES      0.0      0.0    1.0     0.0       0.0       1.0    0.0   0.0   
BORSOD     0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
BUDAPEST   0.0      0.0    0.0     0.0       1.0       0.0    0.0   0.0   
CSONGRAD   1.0      0.0    1.0     0.0       0.0       1.0    0.0   0.0   
FEJER      1.0      0.0    0.0     0.0       0.0       0.0    1.0   0.0   
GYOR       0.0      0.0    0.0     0.0       0.0       0.0    0.0   1.0   
HAJDU      0.0      0.0    1.0     1.0       0.0       0.0    0.0   0.0   
HEVES      0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
JASZ       1.0      0.0    1.0     1.0       0.0       1.0    0.0   0.0   
KOMAROM    0.0      0.0    0.0     0.0       0.0       0.0    1.0   1.0   
NOGRAD     0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
PEST       1.0      0.0    0.0     0.0       1.0       0.0    1.0   0.0   
SOMOGY     0.0      1.0    0.0     0.0       0.0       0.0    1.0   0.0   
SZABOLCS   0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
TOLNA      1.0      1.0    0.0     0.0       0.0       0.0    1.0   0.0   
VAS        0.0      0.0    0.0     0.0       0.0       0.0    0.0   1.0   
VESZPREM   0.0      0.0    0.0     0.0       0.0       0.0    1.0   1.0   
ZALA       0.0      0.0    0.0     0.0       0.0       0.0    0.0   0.0   

          HAJDU  HEVES  JASZ  KOMAROM  NOGRAD  PEST  SOMOGY  SZABOLCS  TOLNA  \
BACS        0.0    0.0   1.0      0.0     0.0   1.0     0.0       0.0    1.0   
BARANYA     0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
BEKES       1.0    0.0   1.0      0.0     0.0   0.0     0.0       0.0    0.0   
BORSOD      1.0    1.0   1.0      0.0     1.0   0.0     0.0       1.0    0.0   
BUDAPEST    0.0    0.0   0.0      0.0     0.0   1.0     0.0       0.0    0.0   
CSONGRAD    0.0    0.0   1.0      0.0     0.0   0.0     0.0       0.0    0.0   
FEJER       0.0    0.0   0.0      1.0     0.0   1.0     1.0       0.0    1.0   
GYOR        0.0    0.0   0.0      1.0     0.0   0.0     0.0       0.0    0.0   
HAJDU       1.0    0.0   1.0      0.0     0.0   0.0     0.0       1.0    0.0   
HEVES       0.0    1.0   1.0      0.0     1.0   1.0     0.0       0.0    0.0   
JASZ        1.0    1.0   1.0      0.0     0.0   1.0     0.0       0.0    0.0   
KOMAROM     0.0    0.0   0.0      1.0     0.0   1.0     0.0       0.0    0.0   
NOGRAD      0.0    1.0   0.0      0.0     1.0   1.0     0.0       0.0    0.0   
PEST        0.0    1.0   1.0      1.0     1.0   1.0     0.0       0.0    0.0   
SOMOGY      0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
SZABOLCS    1.0    0.0   0.0      0.0     0.0   0.0     0.0       1.0    0.0   
TOLNA       0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
VAS         0.0    0.0   0.0      0.0     0.0   0.0     0.0       0.0    0.0   
VESZPREM    0.0    0.0   0.0      1.0     0.0   0.0     1.0       0.0    0.0   
ZALA        0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    0.0   

          VAS  VESZPREM  ZALA  
BACS      0.0       0.0   0.0  
BARANYA   0.0       0.0   0.0  
BEKES     0.0       0.0   0.0  
BORSOD    0.0       0.0   0.0  
BUDAPEST  0.0       0.0   0.0  
CSONGRAD  0.0       0.0   0.0  
FEJER     0.0       1.0   0.0  
GYOR      1.0       1.0   0.0  
HAJDU     0.0       0.0   0.0  
HEVES     0.0       0.0   0.0  
JASZ      0.0       0.0   0.0  
KOMAROM   0.0       1.0   0.0  
NOGRAD    0.0       0.0   0.0  
PEST      0.0       0.0   0.0  
SOMOGY    0.0       1.0   1.0  
SZABOLCS  0.0       0.0   0.0  
TOLNA     0.0       0.0   0.0  
VAS       1.0       1.0   1.0  
VESZPREM  1.0       1.0   1.0  
ZALA      1.0       1.0   1.0

### Other approach (Loading it in torch_geometric.data.Data object)

In [8]:
!pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.4 MB/s eta 0:00:00


In [14]:
from torch_geometric.data import Data
from torch_geometric.utils import to_dense_adj
import torch


In [13]:
# get Adj List
edge_list = torch.tensor(chickenpox_edges_dataset[["id_1", "id_2"]].to_numpy(), dtype=torch.long)
print(edge_list[:3])
print()

# Convert to torch geometric data object
data = Data(x=chickenpox_features_dataset.values, edge_index=edge_list.t().contiguous())

# Add information
data.num_nodes = data.x.shape[1]
data.num_temp_features = data.x.shape[0]

# Add additional information to the data object
data.dates = chickenpox_features_dataset.index.tolist() # Need to convert it back to a list because PyG does not support pd.DatetimeIndex
data.county_names = chickenpox_features_dataset.columns.tolist()

# b)
# Number of nodes:
print("Number of nodes: ", data.num_nodes)

# Number of edges:
print("Number of edges: ", data.num_edges)

# Number of temporal features per node:
print("Number of temporal features per node: ", data.num_temp_features)
print()
print(data)



tensor([[ 0, 10],
        [ 0,  0],
        [ 0,  1]])

Number of nodes:  20
Number of edges:  102
Number of temporal features per node:  522

Data(x=[522, 20], edge_index=[2, 102], num_nodes=20, num_temp_features=522, dates=[522], county_names=[20])


In [15]:
# c)
adj_mat = to_dense_adj(data.edge_index, max_num_nodes=data.num_nodes).squeeze().numpy()
print(adj_mat)


[[1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.

# Task 2: Load the dataset into pytorch-geometric-temporal.

## a) Load the dataset with the class: ChickenpoxDatasetLoader

## b) Identify the differences between loading the raw dataset from Task 1 and the processed dataset from this task.

# Task 3: Define a model using pytorch-geometric-temporal

## i. Split the dataset into train and test.


## ii. Train your model on the training dataset



## iii. Test your model on the test dataset and evaluate it for MSE.

# Task 4: Set up a hyperparameter optimization pipeline with nested 5-fold cross-validation.

## i. Familiarize yourself with the hyperparameter optimization package optuna (https://optuna.org/ ).


## ii. Integrate the logging package mlflow (https://mlflow.org/) to log your metrics.


## iii. Train and test your models and report the evaluation metrics with mean and standard deviation for the nested CV.

# Task 5: Test implementations of 3 different models (such as GConvLSTM, GConvGRU, STGCN, DCRNN) and find out the best performing model


# Task 6: Compare your results with the following study: https://arxiv.org/abs/2102.08100