<a href="https://colab.research.google.com/github/JulianMeigen/ML-handson/blob/main/notebooks/8.0-SNJMMH-Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment Day 8

## Team members:
- Samuel Nebgen s6sanebg@uni-bonn.de
- Muhammad Humza Arain s27marai@uni-bonn.de
- Julian Meigen s82jmeig@uni-bonn.de

## 17.09.2025

Contributions were made by all team members in around the same amount, either based on discussions or coding.

# Task 1: Understand the dataset

In [1]:
!gdown --folder https://drive.google.com/drive/folders/1w_3J7hXOKd4IEEkQp25c0-3-IU1Qqmzp?usp=sharing

Retrieving folder contents
Processing file 1i-YvTQv7dO4EhsZoIFbQj6WJWRNdTZ16 hungary_chickenpox.csv
Processing file 1idipHj2FqgyKfhDqVne3xRyVxW5gnqEq hungary_county_edges.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1i-YvTQv7dO4EhsZoIFbQj6WJWRNdTZ16
To: /content/Day_8/hungary_chickenpox.csv
100% 35.1k/35.1k [00:00<00:00, 55.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1idipHj2FqgyKfhDqVne3xRyVxW5gnqEq
To: /content/Day_8/hungary_county_edges.csv
100% 1.85k/1.85k [00:00<00:00, 7.74MB/s]
Download completed


## a) Load the dataset Hungarian Chickenpox

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import os



In [3]:
chickenpox_features_dataset = pd.read_csv(os.path.join('Day_8', 'hungary_chickenpox.csv'), index_col=0)
chickenpox_edges_dataset = pd.read_csv(os.path.join('Day_8', 'hungary_county_edges.csv'))

## b) Identify the number of edges, nodes, and temporal features.

In [4]:
print(f'The number of edges in the dataset is {chickenpox_edges_dataset.shape[0]}')

The number of edges in the dataset is 102


In [5]:
print(f'The number of nodes in the dataset is {chickenpox_features_dataset.shape[1]}')


The number of nodes in the dataset is 20


In [6]:
print(f'The number of temporal features is {chickenpox_features_dataset.shape[0]}')

The number of temporal features is 522


## c) Plot the adjacency matrix of the counties.

In [7]:
adjacency_matrix = np.zeros((chickenpox_features_dataset.shape[1], chickenpox_features_dataset.shape[1]))

for id_1, id_2 in zip(chickenpox_edges_dataset['id_1'], chickenpox_edges_dataset['id_2']):
    adjacency_matrix[id_1, id_2] = 1
    adjacency_matrix[id_2, id_1] = 1


header = list(chickenpox_edges_dataset['name_1'].unique())
index = list(chickenpox_edges_dataset['name_1'].unique())
adjacency_df = pd.DataFrame(data = adjacency_matrix, columns=header, index=index)

adjacency_df

BACS  BARANYA  BEKES  BORSOD  BUDAPEST  CSONGRAD  FEJER  GYOR  \
BACS       1.0      1.0    0.0     0.0       0.0       1.0    1.0   0.0   
BARANYA    1.0      1.0    0.0     0.0       0.0       0.0    0.0   0.0   
BEKES      0.0      0.0    1.0     0.0       0.0       1.0    0.0   0.0   
BORSOD     0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
BUDAPEST   0.0      0.0    0.0     0.0       1.0       0.0    0.0   0.0   
CSONGRAD   1.0      0.0    1.0     0.0       0.0       1.0    0.0   0.0   
FEJER      1.0      0.0    0.0     0.0       0.0       0.0    1.0   0.0   
GYOR       0.0      0.0    0.0     0.0       0.0       0.0    0.0   1.0   
HAJDU      0.0      0.0    1.0     1.0       0.0       0.0    0.0   0.0   
HEVES      0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
JASZ       1.0      0.0    1.0     1.0       0.0       1.0    0.0   0.0   
KOMAROM    0.0      0.0    0.0     0.0       0.0       0.0    1.0   1.0   
NOGRAD     0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
PEST       1.0      0.0    0.0     0.0       1.0       0.0    1.0   0.0   
SOMOGY     0.0      1.0    0.0     0.0       0.0       0.0    1.0   0.0   
SZABOLCS   0.0      0.0    0.0     1.0       0.0       0.0    0.0   0.0   
TOLNA      1.0      1.0    0.0     0.0       0.0       0.0    1.0   0.0   
VAS        0.0      0.0    0.0     0.0       0.0       0.0    0.0   1.0   
VESZPREM   0.0      0.0    0.0     0.0       0.0       0.0    1.0   1.0   
ZALA       0.0      0.0    0.0     0.0       0.0       0.0    0.0   0.0   

          HAJDU  HEVES  JASZ  KOMAROM  NOGRAD  PEST  SOMOGY  SZABOLCS  TOLNA  \
BACS        0.0    0.0   1.0      0.0     0.0   1.0     0.0       0.0    1.0   
BARANYA     0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
BEKES       1.0    0.0   1.0      0.0     0.0   0.0     0.0       0.0    0.0   
BORSOD      1.0    1.0   1.0      0.0     1.0   0.0     0.0       1.0    0.0   
BUDAPEST    0.0    0.0   0.0      0.0     0.0   1.0     0.0       0.0    0.0   
CSONGRAD    0.0    0.0   1.0      0.0     0.0   0.0     0.0       0.0    0.0   
FEJER       0.0    0.0   0.0      1.0     0.0   1.0     1.0       0.0    1.0   
GYOR        0.0    0.0   0.0      1.0     0.0   0.0     0.0       0.0    0.0   
HAJDU       1.0    0.0   1.0      0.0     0.0   0.0     0.0       1.0    0.0   
HEVES       0.0    1.0   1.0      0.0     1.0   1.0     0.0       0.0    0.0   
JASZ        1.0    1.0   1.0      0.0     0.0   1.0     0.0       0.0    0.0   
KOMAROM     0.0    0.0   0.0      1.0     0.0   1.0     0.0       0.0    0.0   
NOGRAD      0.0    1.0   0.0      0.0     1.0   1.0     0.0       0.0    0.0   
PEST        0.0    1.0   1.0      1.0     1.0   1.0     0.0       0.0    0.0   
SOMOGY      0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
SZABOLCS    1.0    0.0   0.0      0.0     0.0   0.0     0.0       1.0    0.0   
TOLNA       0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    1.0   
VAS         0.0    0.0   0.0      0.0     0.0   0.0     0.0       0.0    0.0   
VESZPREM    0.0    0.0   0.0      1.0     0.0   0.0     1.0       0.0    0.0   
ZALA        0.0    0.0   0.0      0.0     0.0   0.0     1.0       0.0    0.0   

          VAS  VESZPREM  ZALA  
BACS      0.0       0.0   0.0  
BARANYA   0.0       0.0   0.0  
BEKES     0.0       0.0   0.0  
BORSOD    0.0       0.0   0.0  
BUDAPEST  0.0       0.0   0.0  
CSONGRAD  0.0       0.0   0.0  
FEJER     0.0       1.0   0.0  
GYOR      1.0       1.0   0.0  
HAJDU     0.0       0.0   0.0  
HEVES     0.0       0.0   0.0  
JASZ      0.0       0.0   0.0  
KOMAROM   0.0       1.0   0.0  
NOGRAD    0.0       0.0   0.0  
PEST      0.0       0.0   0.0  
SOMOGY    0.0       1.0   1.0  
SZABOLCS  0.0       0.0   0.0  
TOLNA     0.0       0.0   0.0  
VAS       1.0       1.0   1.0  
VESZPREM  1.0       1.0   1.0  
ZALA      1.0       1.0   1.0

### Other approach (Loading it in torch_geometric.data.Data object)

In [8]:
!pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 19.4 MB/s eta 0:00:00


In [9]:
from torch_geometric.data import Data
from torch_geometric.utils import to_dense_adj
import torch


In [10]:
# get Adj List
edge_list = torch.tensor(chickenpox_edges_dataset[["id_1", "id_2"]].to_numpy(), dtype=torch.long)
print(edge_list[:3])
print()

# Convert to torch geometric data object
data = Data(x=chickenpox_features_dataset.values, edge_index=edge_list.t().contiguous())

# Add information
data.num_nodes = data.x.shape[1]
data.num_temp_features = data.x.shape[0]

# Add additional information to the data object
data.dates = chickenpox_features_dataset.index.tolist() # Need to convert it back to a list because PyG does not support pd.DatetimeIndex
data.county_names = chickenpox_features_dataset.columns.tolist()

# b)
# Number of nodes:
print("Number of nodes: ", data.num_nodes)

# Number of edges:
print("Number of edges: ", data.num_edges)

# Number of temporal features per node:
print("Number of temporal features per node: ", data.num_temp_features)
print()
print(data)



tensor([[ 0, 10],
        [ 0,  0],
        [ 0,  1]])

Number of nodes:  20
Number of edges:  102
Number of temporal features per node:  522

Data(x=[522, 20], edge_index=[2, 102], num_nodes=20, num_temp_features=522, dates=[522], county_names=[20])


In [11]:
# c)
adj_mat = to_dense_adj(data.edge_index, max_num_nodes=data.num_nodes).squeeze().numpy()
print(adj_mat)


[[1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0.

# Task 2: Load the dataset into pytorch-geometric-temporal.

## a) Load the dataset with the class: ChickenpoxDatasetLoader

In [12]:
!pip install torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-2.8.0+cu126.html

Looking in links: https://data.pyg.org/whl/torch-2.8.0+cu126.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 30.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 58.0 MB/s eta 0:00:00


In [13]:
!pip install torch_geometric_temporal

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 2.0 MB/s eta 0:00:00


In [14]:
from torch_geometric_temporal.dataset import ChickenpoxDatasetLoader

loader = ChickenpoxDatasetLoader()

dataset = loader.get_dataset()

## b) Identify the differences between loading the raw dataset from Task 1 and the processed dataset from this task.

In [15]:
print(dataset[0])

Data(x=[20, 4], edge_index=[2, 102], edge_attr=[102], y=[20])


In [16]:
print(dataset.features[0][0:2])

[[-1.08135724e-03  2.85705967e-02  3.54742090e-01  2.95438182e-01]
 [-7.11136085e-01 -5.98430173e-01  1.90511208e-01  1.09215850e+00]]


In [17]:
print(dataset.targets[0][0:2])

[ 0.71056554 -0.07246925]


Because the Labels have been removed, we need to map the county IDs later back to the raw dataset.

# Task 3: Define a model using pytorch-geometric-temporal

## i. Split the dataset into train and test.

In [18]:
from torch_geometric_temporal.signal import temporal_signal_split

In [19]:
train_dataset, test_dataset = temporal_signal_split(dataset, train_ratio=0.8)


print(train_dataset[0])
print(test_dataset[0])
print(len(list(train_dataset)))
print(len(list(test_dataset)))

Data(x=[20, 4], edge_index=[2, 102], edge_attr=[102], y=[20])
Data(x=[20, 4], edge_index=[2, 102], edge_attr=[102], y=[20])
413
104


In [20]:
#for time, snapshot in enumerate(train_dataset):
#    print(f'Time {time}:')
#    print('snapshot', snapshot)


## ii. Train your model on the training dataset


In [21]:
#implement the model
torch.manual_seed(1)
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import DCRNN

class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features, out_channels=32, K=1):
        super(RecurrentGCN, self).__init__()
        self.recurrent = DCRNN(node_features, out_channels, K)
        self.linear = torch.nn.Linear(out_channels, 1)

    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight)
        h = F.relu(h)
        h = self.linear(h)
        return h

In [22]:
#train the model
from tqdm import tqdm
model = RecurrentGCN(node_features=4)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model.train()

for epoch in tqdm(range(200)):
    cost = 0
    for time, snapshot in enumerate(train_dataset):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
    cost = cost / (time+1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()

100%|██████████| 200/200 [02:48<00:00,  1.19it/s]



## iii. Test your model on the test dataset and evaluate it for MSE.

In [23]:
model.eval()
cost = 0
for time, snapshot in enumerate(test_dataset):
    y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
    cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
cost = cost / (time+1)
cost = cost.item()
print("MSE: {:.4f}".format(cost))

MSE: 0.7268


Since our target here is a continous variable and we are doing a Regression (Forecasting the Chickenpox counts based on previous counts), we use MSE (or RMSE), which sums up the squared differnece between the truth and the predicted value. Since it squares the errors, big differneces are stongly penalized but it is also sensitive to outliers.

Beacuse we are doing a regression task its better to use MSE or MAE. If we would do a classification task, metrics such as f1-score or accuracy or AUROC could be used.

# Task 4: Set up a hyperparameter optimization pipeline with nested 5-fold cross-validation.

## i. Familiarize yourself with the hyperparameter optimization package optuna (https://optuna.org/ ).


In [24]:
class RGCNoptimization:
    def __init__(self, train_dataset, val_dataset, input_feature=4, study_name="GCN_optimization"):
        self.data = data
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.input_feature = input_feature

        self.study_name = study_name
        self.storage_name = "sqlite:///{}.db".format(self.study_name)
        self.study = optuna.create_study(study_name=self.study_name, storage=self.storage_name, load_if_exists=True)

    def objective(self, trial):
        # Define the hyperparameters to optimize

        out_channels = trial.suggest_int("out_channels", 16, 128) # Changed from suggest_float to suggest_int
        K = trial.suggest_int("K", 1, 5)
        LR = trial.suggest_float("LR", 0.001, 0.1)

        # Create the GCN model with the suggested hyperparameters
        model = RecurrentGCN(self.input_feature, out_channels, K)

        # Train the model
        optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=5e-4)
        criterion = torch.nn.MSELoss()

        # Training loop
        epochs = 100
        model.train()
        for epoch in range(1, epochs + 1):
          loss = 0
          for time, snapshot in enumerate(self.train_dataset):
            optimizer.zero_grad()
            out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
            loss = loss + criterion(out, snapshot.y)

          loss = loss / (time+1)
          loss.backward()
          optimizer.step()


        # Validate the model
        model.eval()
        with torch.no_grad():
          loss = 0
          for time, snapshot in enumerate(self.val_dataset):
            optimizer.zero_grad()
            out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
            loss = loss + criterion(out, snapshot.y)
          loss = loss / (time+1)

        return loss.item()

## ii. Integrate the logging package mlflow (https://mlflow.org/) to log your metrics.


## iii. Train and test your models and report the evaluation metrics with mean and standard deviation for the nested CV.

In [25]:
!pip install optuna

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 9.6 MB/s eta 0:00:00


In [26]:
!pip install wandb -q

In [27]:
import optuna

In [28]:
 #Ignore excessive warnings
import logging
logging.propagate = False
logging.getLogger().setLevel(logging.ERROR)

# WandB – Import the wandb library
import wandb

In [29]:
!wandb login

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
Aborted!
^C


In [30]:
from sklearn.model_selection import TimeSeriesSplit

In [31]:
dataset.snapshot_count

517

In [32]:
1 - 10/517

0.9806576402321083

In [33]:
# getting last 10 Weeks as Model-test set which will be indepoendend of our training. Its needed to compare the models in the end.
data, model_test = temporal_signal_split(dataset, train_ratio= 1-10/517)

In [34]:
data.snapshot_count, model_test.snapshot_count

(507, 10)

In [35]:
dataset_lst = list(data)
n_splits_outer = 5
tscv = TimeSeriesSplit(n_splits=3)

idx = np.arange(len(dataset_lst))
for train_val_idx, test_idx in tscv.split(idx):
  train_val_mask = np.isin(idx, train_val_idx)
  test_mask = np.isin(idx, test_idx)

  train_val_dataset_lst = [i for idx, i in enumerate(dataset_lst) if train_val_mask[idx]]
  test_dataset_lst = [i for idx, i in enumerate(dataset_lst) if test_mask[idx]]

  ## Inner Loop
  tscv_inner = TimeSeriesSplit(n_splits=3)
  idx_inner = np.arange(len(train_val_dataset_lst))


  for train_idx, val_idx in tscv_inner.split(idx_inner):
    train_mask = np.isin(idx_inner, train_idx)
    val_mask = np.isin(idx_inner, val_idx)

    train_dataset_lst = [i for idx, i in enumerate(train_val_dataset_lst) if train_mask[idx]]
    val_dataset_lst = [i for idx, i in enumerate(train_val_dataset_lst) if val_mask[idx]]


    # Optimize/Train model with optuna
    gcn_op = RGCNoptimization(train_dataset_lst, val_dataset_lst, input_feature=4)
    study = gcn_op.study
    study.optimize(gcn_op.objective, n_trials=10)
    best_params = study.best_params

  ## End Inner Loop


  # Train the best param model
  model = RecurrentGCN(input_feature=4, out_channels=best_params["out_channels"], K=best_params["K"])
  optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
  criterion = torch.nn.MSELoss()

  # Training loop

  epochs = 100
  model.train()
  for epoch in range(1, epochs + 1):
    loss = 0
    for time, snapshot in enumerate(train_val_dataset_lst):
      optimizer.zero_grad()
      out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
      loss = loss + criterion(out, snapshot.y)

    loss = loss / (time+1)
    loss.backward()
    optimizer.step()


  # Validate the model
  model.eval()
  with torch.no_grad():
    loss = 0
    for time, snapshot in enumerate(test_dataset_lst):
      optimizer.zero_grad()
      out = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)  # forward pass
      loss = loss + criterion(out, snapshot.y)
    loss = loss / (time+1)

[I 2025-09-17 16:42:49,742] A new study created in RDB with name: GCN_optimization
/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([20])) that is different to the input size (torch.Size([20, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
[I 2025-09-17 16:42:59,721] Trial 0 finished with value: 1.0029993057250977 and parameters: {'out_channels': 34, 'K': 2, 'LR': 0.05850961214044743}. Best is trial 0 with value: 1.0029993057250977.
[I 2025-09-17 16:43:20,716] Trial 1 finished with value: 0.976468026638031 and parameters: {'out_channels': 119, 'K': 3, 'LR': 0.0035880086030488545}. Best is trial 1 with value: 0.976468026638031.
[I 2025-09-17 16:43:49,372] Trial 2 finished with value: 1.026472806930542 and parameters: {'out_channels': 75, 'K': 5, 'LR': 0.03825912452202509}. Best is trial 1 with value: 0

TypeError: RecurrentGCN.__init__() got an unexpected keyword argument 'input_feature'

# Task 5: Test implementations of 3 different models (such as GConvLSTM, GConvGRU, STGCN, DCRNN) and find out the best performing model


In [62]:

import torch
import torch.nn.functional as F
from torch import nn
from tqdm import tqdm
from torch_geometric_temporal.dataset import ChickenpoxDatasetLoader
from torch_geometric_temporal.nn.recurrent import DCRNN

torch.manual_seed(1)

lags = 8
loader = ChickenpoxDatasetLoader()
dataset = loader.get_dataset(lags=lags)   # reload for lags equal to 8
snapshots = [s for s in dataset]
#print(snapshots)

In [41]:
split = int(0.8 * len(snapshots))
train_snaps = snapshots[:split]
test_snaps  = snapshots[split:]


410
103


In [59]:
# First implementing our Model in the same way as described in the Paper:

import torch
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import DCRNN, GConvLSTM, GConvGRU

torch.manual_seed(1)
snapshots = [s for s in dataset]          # list of temporal snapshots

split = int(0.8 * len(snapshots))
train_snaps = snapshots[:split]
test_snaps  = snapshots[split:]


class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features= 8, hidden_channels = 32):
        super(RecurrentGCN, self).__init__()
        # DCRNN: input_dim -> hidden_dim -> output_dim
        self.recurrent = DCRNN(in_channels=node_features, out_channels=hidden_channels, K=1)
        self.linear = torch.nn.Linear(hidden_channels, 1)

    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight)
        h = F.relu(h)
        h = self.linear(h)
        return h.squeeze()


class RecurrentGCN_GConvLSTM(torch.nn.Module):
    def __init__(self, node_features= 8, hidden_channels = 32):
        super(RecurrentGCN_GConvLSTM, self).__init__()
        self.recurrent = GConvLSTM(in_channels=node_features, out_channels=hidden_channels, K=1)
        self.linear = torch.nn.Linear(hidden_channels, 1)

    def forward(self, x, edge_index, edge_weight):
        h,_ = self.recurrent(x, edge_index, edge_weight)

        h = F.relu(h)
        h = self.linear(h)
        return h.squeeze()


class RecurrentGCN_GConvGRU(torch.nn.Module):
    def __init__(self, node_features= 8, hidden_channels = 32):
        super(RecurrentGCN_GConvGRU, self).__init__()
        self.recurrent = GConvGRU(in_channels=node_features, out_channels=hidden_channels, K=1)
        self.linear = torch.nn.Linear(hidden_channels, 1)

    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight)
        h = F.relu(h)
        h = self.linear(h)
        return h.squeeze()

In [55]:
model_DCRNN = RecurrentGCN(node_features=8, hidden_channels=32)
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

# training the model
model_DCRNN.train()

for epoch in tqdm(range(200)):
    cost = 0
    for time, snapshot in enumerate(train_snaps):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
    cost = cost / (time+1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()

100%|██████████| 200/200 [02:53<00:00,  1.15it/s]


In [52]:
model_GConvGRU= RecurrentGCN_GConvGRU(node_features=8, hidden_channels=32)

# training the model
model_GConvGRU.train()

for epoch in tqdm(range(200)):
    cost = 0
    for time, snapshot in enumerate(train_snaps):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
    cost = cost / (time+1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()

100%|██████████| 200/200 [02:44<00:00,  1.22it/s]


In [60]:
model_GConvLSTM= RecurrentGCN_GConvLSTM(node_features=8, hidden_channels=32)

# training the model
model_GConvLSTM.train()

for epoch in tqdm(range(200)):
    cost = 0
    for time, snapshot in enumerate(train_snaps):
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat.squeeze() - snapshot.y)**2)
    cost = cost / (time+1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()

100%|██████████| 200/200 [02:44<00:00,  1.22it/s]


In [61]:

@torch.no_grad()
def eval_horizon(model, snaps, horizon=10):
    model.eval()
    mse_sum, count = 0.0, 0

    # We need at least `horizon` steps ahead available in the split
    # If snaps cover indices [0..Ttest-1], last valid start is Ttest - horizon
    T = len(snaps)
    last_start = T - horizon
    if last_start <= 0:
        raise ValueError("Not enough test steps to evaluate this horizon.")

    for t in range(last_start):
        # fixed graph structure for this dataset; take from start t
        base = snaps[t]
        ei = base.edge_index.to(device)
        ew = None if base.edge_attr is None else base.edge_attr.to(device)

        # initialize lag window with actual lags at time t
        x = base.x.to(device).clone()  # (num_nodes, lags)

        # roll out predictions for h=1..horizon
        for h in range(1, horizon + 1):
            y_pred = model(x, ei, ew)  # (num_nodes,)
            if h < horizon:
                # shift lags left and append current prediction
                x = torch.cat([x[:, 1:], y_pred.unsqueeze(-1)], dim=1)

        # ground truth at t + horizon (the value we aimed to predict)
        y_true = snaps[t + horizon - 0].y.to(device).squeeze(-1)  # t+horizon corresponds to next target after lags

        mse = F.mse_loss(y_pred, y_true).item()
        mse_sum += mse
        count += 1

    return mse_sum / count

horizon_10_mse_DCRNN = eval_horizon(model_DCRNN, test_snaps, horizon=10)
horizon_10_mse_GConvGRU = eval_horizon(model_GConvGRU, test_snaps, horizon=10)
horizon_10_mse_GConvLSTM = eval_horizon(model_GConvLSTM, test_snaps, horizon=10)

print(f"10-week horizon MSE DCRNN: {horizon_10_mse:.4f}")
print(f"10-week horizon MSE GConvGRU: {horizon_10_mse:.4f}")
print(f"10-week horizon MSE GConvLSTM: {horizon_10_mse:.4f}")



10-week horizon MSE DCRNN: 0.9832
10-week horizon MSE GConvGRU: 0.9832
10-week horizon MSE GConvLSTM: 0.9832


# Task 6: Compare your results with the following study: https://arxiv.org/abs/2102.08100

Compared to the results with the Models from the study, our models achieved a slightly worse MSE averaged over a ten week horizon